version: '3.4'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0  
    container_name: api
    ports:
      - "5000:80"
    networks:
      - backend
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=mada_immo;User=sa;Password=Pass2024;


  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
